from libraries.tinylog import TinyLog

#----------------------------------------------
# CONFIG FILE : THE CONTAINER OF ALL PARAMETERS
# PLEASE UPDATE THESE VALUES TO YOUR NEEDS.
# NO IMPORTANT PARAMETER SHALL BE HARDCODED.
# ALL SHALL BE IN THIS CONFIG FILE.
#----------------------------------------------

# --- PIN DEFINITIONS ---
LED_PIN = 2
NEO6M_RX_PIN = 5
NEO6M_TX_PIN = 4

IN1_PIN = 37
IN2_PIN = 38
ENA_PIN = 45
IN3_PIN = 46
IN4_PIN = 47
ENB_PIN = 48

HALL_LEFT_PIN = 36
HALL_RIGHT_PIN = 18

# --- MOTOR AND TRANSMISSION PARAMETERS ---
MOTOR_MAX_RPM = 2000 # Set this to the lowest of the two motors
PID_P = 1
PID_I = 0.25
PID_D = 0.5

# --- GPS PARAMETERS ---
UART_ID_GPS = 1

# --- LOG PARAMETERS ---
LOG_LEVEL = TinyLog.DEBUG

# --- WIFI PARAMETERS ---
WIFI_SSID = "Team4-BP"
WIFI_PASSWORD = "sodastream-mitosis"
WIFI_MAX_CLIENTS = 10

# --- SERVER PARAMETERS ---
SERVER_PORT = 80
